language: rust
sudo: false
cache: cargo
rust:
  - nightly-2017-01-26

script:
  - cargo test
  - cargo rustc -- -D warnings

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
