language: rust
rust:
  - nightly
sudo: false

script:
  - cargo test --verbose
  - cargo build --release --verbose
  - cargo rustc --release -- -D warnings

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
