[package]
name = "grarr"
version = "0.0.1"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]

git-appraise = { git = "https://github.com/Nemo157/git-appraise-rs" }
git2 = { git = "https://github.com/alexcrichton/git2-rs" }

hyper = "*"
iron = "*"
router = { git = "https://github.com/Nemo157/router", rev = "reverse_priority" }
persistent = { git = "https://github.com/iron/persistent" }
logger = { git = "https://github.com/iron/logger" }
typemap = "*"
mime = "*"
lru_time_cache = "*"
time = "*"
walkdir = "0.1.5"

chrono = "*"
pulldown-cmark = "*"
maud-pulldown-cmark = { git = "https://git.nemo157.com/rust/maud-pulldown-cmark.git", rev = "maud-consuming-render" }
gravatar = { git = "https://github.com/Nemo157/rust-gravatar", rev = "fix-type-resolve-failure" }

maud = { git = "https://git.nemo157.com/forks/maud.git", rev = "combined2" }
maud_macros = { git = "https://git.nemo157.com/forks/maud.git", rev = "combined2" }
