[package]
name = "grarr"
version = "0.0.2"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]

git-appraise = { git = "https://github.com/Nemo157/git-appraise-rs" }
git2 = { git = "https://github.com/alexcrichton/git2-rs" }

hyper = "*"
iron = "*"
router = { git = "https://github.com/Nemo157/router", rev = "reverse_priority" }
logger = { git = "https://github.com/iron/logger" }
typemap = "*"
mime = "*"
lru_time_cache = "*"
time = "*"
walkdir = "*"

chrono = "*"
pulldown-cmark = "*"
maud-pulldown-cmark = { git = "https://git.nemo157.com/rust/maud-pulldown-cmark.git", rev = "maud-update" }
gravatar = { git = "https://github.com/Nemo157/rust-gravatar", rev = "fix-type-resolve-failure" }

maud = { git = "https://github.com/lfairy/maud" }
maud_macros = { git = "https://github.com/lfairy/maud" }

clippy = { version = "*" }
rust-crypto = { version = "*" }
unicase = { version = "*" }
