[package]
name = "grarr"
version = "0.0.3"
authors = ["Wim Looman <wim@nemo157.com>"]
build = "build.rs"

[features]
# "maybe_cache" enables "cache" when building in release profile
default = ["clippy", "maybe_cache"]
cache = ["maybe_cache"]
maybe_cache = []

[dependencies]

git-appraise = { git = "https://github.com/Nemo157/git-appraise-rs" }
git2 = "0.4.2"

hyper = "*"
iron = "*"
router = { git = "https://github.com/Nemo157/router", rev = "reverse_priority" }
logger = { git = "https://github.com/Nemo157/logger", rev = "allow-no-status" }
typemap = "*"
mime = "*"
lru_time_cache = "*"
time = "*"
walkdir = "*"
params = "*"

chrono = "*"
pulldown-cmark = "*"
maud-pulldown-cmark = { git = "https://github.com/Nemo157/maud-pulldown-cmark", rev = "maud-update" }
gravatar = "0.1.4"

maud = { git = "https://github.com/lfairy/maud" }
maud_macros = { git = "https://github.com/lfairy/maud" }

clippy = { version = "*", optional = true }
rust-crypto = { version = "*" }
unicase = { version = "*" }
