[package]
name = "git-appraise-server"
version = "0.0.1"
authors = ["Wim Looman <wim@nemo157.com>"]

[dependencies]

git-appraise = { git = "https://github.com/Nemo157/git-appraise-rs" }

iron = "*"
router = { git = "https://github.com/iron/router" }
persistent = { git = "https://github.com/iron/persistent" }
logger = { git = "https://github.com/iron/logger" }
typemap = "*"

chrono = "*"
pulldown-cmark = "*"
maud-pulldown-cmark = "*"

maud = "*"
maud_macros = { git = "https://git.nemo157.com/forks/maud.git", rev = "combined" }
